ALTER TABLE events ADD COLUMN IF NOT EXISTS city VARCHAR;
ALTER TABLE events ADD COLUMN IF NOT EXISTS state VARCHAR;
ALTER TABLE events ADD COLUMN IF NOT EXISTS country VARCHAR DEFAULT 'Nigeria';
ALTER TABLE events ADD COLUMN IF NOT EXISTS latitude FLOAT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS longitude FLOAT;
