"""add slug to events

Revision ID: 53d08c57b02d
Revises: 2c4f8e1a3b5d
Create Date: 2026-05-31 11:35:44.680973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d08c57b02d'
down_revision: Union[str, None] = '2c4f8e1a3b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_column('events', 'slug')
    # ### end Alembic commands ###
