"""add invite_sent to guests

Revision ID: a1f237b19e70
Revises: 53d08c57b02d
Create Date: 2026-05-31 11:54:01.570938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f237b19e70'
down_revision: Union[str, None] = '53d08c57b02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('invite_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'invite_sent')
    # ### end Alembic commands ###
